import { FormEvent, useEffect, useState } from 'react';
import { motion } from 'framer-motion';
import { TbArrowUpRight, TbBrandGithub, TbCheck, TbChevronDown, TbExternalLink, TbMail, TbMapPin, TbMenu2, TbMoon, TbSend, TbSun, TbX } from 'react-icons/tb';
import { certifications } from '../../data/certifications';
import { experienceItems } from '../../data/experience';
import { personalInfo, socialLinks } from '../../data/personal';
import { projects } from '../../data/projects';
import { skillCategories } from '../../data/skills';
import type { ContactFormErrors, ContactFormValues } from '../../types';
import { hasValidationErrors, validateContactForm } from '../../utils/validation';

const nav = [['About','about'],['Work','projects'],['Hackathon','hackathon'],['Experience','experience'],['Skills','skills'],['Credentials','certifications'],['Contact','contact']] as const;
const hackathonTeam = ['Mahesh Raskar', 'Sankalp Gadakh', 'Arati Dhore', 'Dnyaneshwari Vairale'];

export function DesktopPortfolio() {
  const [theme, setTheme] = useState<'light'|'dark'>(() => { const saved=localStorage.getItem('portfolio-theme'); return saved==='light'||saved==='dark'?saved:(matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light'); });
  const [menuOpen,setMenuOpen]=useState(false);
  useEffect(()=>{document.documentElement.dataset.theme=theme;localStorage.setItem('portfolio-theme',theme)},[theme]);
  const go=(id:string)=>{document.getElementById(id)?.scrollIntoView({behavior:'smooth'});setMenuOpen(false)};
  return <div className="portfolio-shell">
    <header className="site-header"><div className="nav-wrap"><button className="wordmark" onClick={()=>go('home')} aria-label="Go home">MR<span>.</span></button><nav className={menuOpen?'site-nav open':'site-nav'} aria-label="Primary navigation">{nav.map(([label,id])=><button key={id} onClick={()=>go(id)}>{label}</button>)}</nav><div className="nav-actions"><button className="icon-button" onClick={()=>setTheme(theme==='dark'?'light':'dark')} aria-label={`Use ${theme==='dark'?'light':'dark'} theme`}>{theme==='dark'?<TbSun/>:<TbMoon/>}</button><a className="header-cta" href={personalInfo.resumeUrl} target="_blank" rel="noreferrer">Résumé <TbArrowUpRight/></a><button className="icon-button menu-button" onClick={()=>setMenuOpen(!menuOpen)} aria-label="Toggle navigation" aria-expanded={menuOpen}>{menuOpen?<TbX/>:<TbMenu2/>}</button></div></div></header>
    <main>
      <section className="hero section" id="home"><div className="hero-copy"><p className="availability"><span/> Available for opportunities</p><h1>I build thoughtful digital products <em>from idea to launch.</em></h1><p className="hero-lede">Full-stack developer and AI builder based in Pune, creating reliable applications, intelligent systems, and polished user experiences.</p><div className="hero-actions"><button className="button primary" onClick={()=>go('projects')}>Explore my work <TbArrowUpRight/></button><button className="button secondary" onClick={()=>go('contact')}>Let’s work together</button></div></div><div className="hero-profile"><div className="profile-monogram">MR</div><div><strong>{personalInfo.name}</strong><span>{personalInfo.role}</span></div><p>{personalInfo.about}</p><div className="profile-meta"><span><TbMapPin/> {personalInfo.location}</span><span><TbCheck/> Open to work</span></div></div><button className="scroll-cue" onClick={()=>go('about')} aria-label="Scroll to about"><TbChevronDown/></button></section>
      <section className="section about-section" id="about"><SectionHead kicker="About" title="Engineering with curiosity and care." description="I enjoy turning complex technical problems into products that feel simple, useful, and dependable."/><div className="about-grid"><p>{personalInfo.objective}</p><div className="numbers"><div><strong>{projects.length}</strong><span>Featured projects</span></div><div><strong>{certifications.length}</strong><span>Credentials</span></div><div><strong>{skillCategories.reduce((n,c)=>n+c.skills.length,0)}+</strong><span>Tools & technologies</span></div></div></div></section>
      <section className="section" id="projects"><SectionHead kicker="Selected work" title="Projects built to solve real problems." description="A selection of full-stack, AI, location-aware, and IoT products."/><div className="project-grid">{projects.map((p,i)=><motion.article className="project-card" key={p.name} initial={{opacity:0,y:16}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.2}}><div className="project-top"><span className="project-number">0{i+1}</span><span className={`status ${p.status==='In Progress'?'progress':''}`}><i/> {p.status}</span></div><h3>{p.name}</h3><p>{p.description}</p><div className="tag-list">{p.stack.map(x=><span key={x}>{x}</span>)}</div><div className="card-links"><a href={p.githubUrl} target="_blank" rel="noreferrer"><TbBrandGithub/> Source</a>{p.liveUrl&&<a href={p.liveUrl} target="_blank" rel="noreferrer">Live site <TbExternalLink/></a>}</div></motion.article>)}</div></section>
      <section className="section hackathon-section" id="hackathon"><SectionHead kicker="Current challenge" title="Building OneOrbit at the AssemblyAI Voice Agent Hackathon." description="A month-long online challenge hosted by lablab.ai and AssemblyAI, focused on the fastest path to a working voice agent."/><div className="hackathon-card"><div className="hackathon-main"><div className="event-meta"><span><i/> Online</span><span>September 1–30, 2026</span><span>$10,000 prize pool</span></div><h3>OneOrbit: AI-Powered Career Automation Platform</h3><p>OneOrbit helps people discover opportunities, match roles to their profile, build ATS-friendly résumés, manage applications, and automate career workflows while keeping people in control of every important action.</p><div className="event-note"><strong>Team idea</strong><span>Building an edge-AI IoT project to solve real-world system telemetry challenges with proactive hardware, mobile UI, and AI collaboration.</span></div></div><aside><p className="section-kicker">Team members</p><ul>{hackathonTeam.map((member,index)=><li key={member}><span>{member.split(' ').map(name=>name[0]).join('')}</span><div><strong>{member}</strong>{index===0&&<small>Team lead</small>}</div></li>)}</ul></aside></div></section>
      <section className="section" id="experience"><SectionHead kicker="Experience" title="Learning by building."/><div className="experience-list">{experienceItems.map(item=><article key={item.company}><div className="experience-date">{item.duration}</div><div className="experience-mark"><span/></div><div className="experience-body"><div className="experience-title"><div><h3>{item.position}</h3><p>{item.company}</p></div><span><TbMapPin/> {item.location}</span></div><ul>{item.responsibilities.map(x=><li key={x}>{x}</li>)}</ul></div></article>)}</div></section>
      <section className="section" id="skills"><SectionHead kicker="Capabilities" title="A practical, modern toolkit." description="Technology chosen around the problem, with a focus on maintainability and clear user outcomes."/><div className="skills-grid">{skillCategories.map(c=>{const Icon=c.icon;return <article key={c.title}><Icon/><h3>{c.title}</h3><p>{c.summary}</p><div className="skill-list">{c.skills.map(s=><span key={s.name}>{s.name}</span>)}</div></article>})}</div></section>
      <section className="section" id="certifications"><SectionHead kicker="Credentials" title="Foundations that keep growing."/><div className="credentials-list">{certifications.map(c=>{const Icon=c.icon;return <a href={c.documentUrl} target="_blank" rel="noreferrer" key={c.title}><span className="credential-icon"><Icon/></span><span><strong>{c.title}</strong><small>{c.issuer}</small></span><TbArrowUpRight/></a>})}</div></section>
      <section className="section contact-section" id="contact"><div className="contact-intro"><p className="section-kicker">Contact</p><h2>Have an idea?<br/>Let’s make it real.</h2><p>I’m always interested in thoughtful products, ambitious teams, and problems worth solving.</p><a href={`mailto:${personalInfo.email}`}><TbMail/> {personalInfo.email}</a><div className="social-row">{socialLinks.filter(l=>l.label!=='Email').map(l=><a href={l.href} target="_blank" rel="noreferrer" key={l.label}>{l.label}<TbArrowUpRight/></a>)}</div></div><ContactForm/></section>
    </main><footer><div><strong>Mahesh Raskar</strong><span>Designing and building from Pune, India.</span></div><button onClick={()=>go('home')}>Back to top ↑</button><small>© {new Date().getFullYear()} Mahesh Raskar</small></footer>
  </div>;
}

function SectionHead({kicker,title,description}:{kicker:string;title:string;description?:string}){return <header className="section-head"><p className="section-kicker">{kicker}</p><h2>{title}</h2>{description&&<p>{description}</p>}</header>}
function ContactForm(){const [values,setValues]=useState<ContactFormValues>({name:'',email:'',subject:'',message:''});const [errors,setErrors]=useState<ContactFormErrors>({});const [sent,setSent]=useState(false);const update=(key:keyof ContactFormValues,value:string)=>setValues(v=>({...v,[key]:value}));const submit=(e:FormEvent)=>{e.preventDefault();const next=validateContactForm(values);setErrors(next);if(hasValidationErrors(next))return;window.location.href=`mailto:${personalInfo.email}?subject=${encodeURIComponent(values.subject)}&body=${encodeURIComponent(`Hi Mahesh,\n\n${values.message}\n\nFrom: ${values.name} (${values.email})`)}`;setSent(true)};return <form className="contact-form" onSubmit={submit} noValidate><div className="field-row"><Field label="Your name" value={values.name} error={errors.name} onChange={v=>update('name',v)}/><Field label="Email address" type="email" value={values.email} error={errors.email} onChange={v=>update('email',v)}/></div><Field label="What’s this about?" value={values.subject} error={errors.subject} onChange={v=>update('subject',v)}/><label className="field"><span>Tell me about your idea</span><textarea rows={5} value={values.message} onChange={e=>update('message',e.target.value)} aria-invalid={!!errors.message}/>{errors.message&&<small>{errors.message}</small>}</label><button className="button primary" type="submit">Send message <TbSend/></button>{sent&&<p className="success"><TbCheck/> Your email app is ready with the message.</p>}</form>}
function Field({label,value,error,onChange,type='text'}:{label:string;value:string;error?:string;onChange:(v:string)=>void;type?:string}){return <label className="field"><span>{label}</span><input type={type} value={value} onChange={e=>onChange(e.target.value)} aria-invalid={!!error}/>{error&&<small>{error}</small>}</label>}
